---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "PRO - Producers and Remixers Organization at UCSD"
keywords:    "PRO, producers and remixers org, producers and remixers organization, ucsd, edm, electronic music, proucsd, proclub"
description: "The official website for the Producers and Remixers Organization at the University of California, San Diego. Created and maintained by Stefan Rimola."
source_link: "https://github.com/srimola/pro-v2"
favicon:     "/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: "UA-72597142-1"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  
